// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJEbe9CS1hYgJgjEuf5J9lXNdRGCSs3e8',
    appId: '1:112420956519:web:ce1f76a6d54885b79067c2',
    messagingSenderId: '112420956519',
    projectId: 'safelane-b84a3',
    authDomain: 'safelane-b84a3.firebaseapp.com',
    storageBucket: 'safelane-b84a3.appspot.com',
    measurementId: 'G-FEVHZ9V795',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBATNrGBk5NnkHElyaqvxQUp40P_kCfWCY',
    appId: '1:112420956519:android:cfa785863ef5513a9067c2',
    messagingSenderId: '112420956519',
    projectId: 'safelane-b84a3',
    storageBucket: 'safelane-b84a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSV78nuNjwoko-nLmJnYnoHuC81H50MfI',
    appId: '1:112420956519:ios:71898dbed538cb429067c2',
    messagingSenderId: '112420956519',
    projectId: 'safelane-b84a3',
    storageBucket: 'safelane-b84a3.appspot.com',
    iosClientId: '112420956519-5jajb5bpufqkudhv2g8inil2ro17be6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.safelane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSV78nuNjwoko-nLmJnYnoHuC81H50MfI',
    appId: '1:112420956519:ios:71898dbed538cb429067c2',
    messagingSenderId: '112420956519',
    projectId: 'safelane-b84a3',
    storageBucket: 'safelane-b84a3.appspot.com',
    iosClientId: '112420956519-5jajb5bpufqkudhv2g8inil2ro17be6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.safelane',
  );
}
